# Generated by Django 4.2.5 on 2023-10-19 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='quiz_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.pageofcourse'),
        ),
        migrations.AddField(
            model_name='pageofcourse',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='page_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageofcourse',
            name='lesson_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='lesson_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name_lesson', to='course.course'),
        ),
        migrations.AddField(
            model_name='inputquiz',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='inputquiz_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inputquiz',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.pageofcourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.ManyToManyField(blank=True, related_name='active_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.quiz'),
        ),
    ]
