# Generated by Django 4.2.5 on 2023-10-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'variant ', 'verbose_name_plural': 'variantlar'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs ', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='inputquiz',
            options={'verbose_name': 'ochiq test ', 'verbose_name_plural': 'ochiq testlar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Dars ', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='pageofcourse',
            options={'verbose_name': 'Sahifa ', 'verbose_name_plural': 'SAhifalar'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Test ', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.pageofcourse')),
            ],
            options={
                'verbose_name': 'eslatma ',
                'verbose_name_plural': 'eslatmalar',
            },
        ),
    ]
