# Generated by Django 4.2.5 on 2023-10-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_choice_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputquiz',
            name='endings',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
