# Generated by Django 4.2.5 on 2023-10-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_inputquiz_endings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputquiz',
            name='question',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pageofcourse',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Code_snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=200)),
                ('answer', models.TextField(max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.pageofcourse')),
            ],
        ),
    ]
