# Generated by Django 4.2.5 on 2023-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_inputquiz_endings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputquiz',
            name='endings',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
