# Generated by Django 4.2.5 on 2023-10-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_inputquiz_endings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputquiz',
            name='new_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=100),
        ),
    ]
